apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-resourcemanager
  template:
    metadata:
      labels:
        app: hadoop-resourcemanager
    spec:
      containers:
        - name: resourcemanager
          image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
          ports:
            - containerPort: 8088
          env:
            - name: CLUSTER_NAME
              value: "hadoop-cluster"
